import { HuggingFaceTransformersEmbeddings } from "@langchain/community/embeddings/huggingface_transformers";
import { CONFIG } from "./config.ts";
import { DocumentProcessor } from "./documentProcessor.ts";
import { type PretrainedOptions } from "@huggingface/transformers";
import { Neo4jVectorStore } from "@langchain/community/vectorstores/neo4j_vector";
import { writeFile, mkdir } from 'node:fs/promises'
import { ChatOpenAI } from "@langchain/openai";
import { AI } from "./ai.ts";

let _neo4jVectorStore = null;

async function clearAll(vectorStore: Neo4jVectorStore, nodeLabel: string): Promise<void> {
    console.log(`🗑️  Cleaning all existing documents...`);

    await vectorStore.query(`MATCH (n:${nodeLabel}) DETACH DELETE n`);

    console.log(`✅ All existing documents deleted successfully!`);
}

try {
    console.log("🚀 Initializing Embbedings system with Neo4j...\n");

    const documentProcessor = new DocumentProcessor(CONFIG.pdf.path, CONFIG.textSplitter);
    const documents = await documentProcessor.loadAndSplit();

    // ==================== STEP 1: GENERATE EMBEDDINGS AND POPULATE NEO4J ====================
    console.log("\n\n🔍 STEP 1: Generating Embeddings and populating NEO4J...\n");
    const embbedings = new HuggingFaceTransformersEmbeddings({
        model: CONFIG.embedding.modelName,
        pretrainedOptions: CONFIG.embedding.pretrainedOptions as PretrainedOptions,
    });

    // NLP = Natural language processing, ou seja, processamento de linguagem natural. Aqui é onde o modelo 
    // de linguagem é inicializado.
    const nlpModel = new ChatOpenAI({ 
        temperature: CONFIG.openRouter.temperature,
        maxRetries: CONFIG.openRouter.maxRetries,
        modelName: CONFIG.openRouter.nlpModel,
        openAIApiKey: CONFIG.openRouter.apiKey,
        configuration:{
            baseURL: CONFIG.openRouter.url,
            defaultHeaders: CONFIG.openRouter.defaultHeaders
        }
    });

    // const response = await embeddings.embedQuery(
    //     "JavaScript"
    // )
    // const response = await embeddings.embedDocuments([
    //     "JavaScript"
    // ])
    // console.log('response', response)

    const response = await embbedings.embedDocuments(documents.map(doc => doc.pageContent));
    console.log(`✅ Embeddings generated by ${response.length} documents`);

    // Cria a configuração do Neo4jVectorStore a partir do grafo existente.
    _neo4jVectorStore = await Neo4jVectorStore.fromExistingGraph(embbedings, CONFIG.neo4j);

    clearAll(_neo4jVectorStore, CONFIG.neo4j.nodeLabel);

    // Popula o grafo com os documentos processados.
    for (const [index, doc] of documents.entries()) {
        console.log(`📌 Inserting document ${index + 1}/${documents.length} into Neo4j...`);
        await _neo4jVectorStore.addDocuments([doc]);
    }

    // ==================== STEP 2: RUN SIMILARITY SEARCH ====================
    console.log("\n\n🔍 STEP 2: Running similarity searches...\n");

    const questions = [
        "O que são tensores e como são representados em JavaScript?",
        "Como converter objetos JavaScript em tensores?",
        "O que é normalização de dados e por que é necessária?",
        // "Como funciona uma rede neural no TensorFlow.js?",
        // "O que significa treinar uma rede neural?",
        // "o que é hot enconding e quando usar?"
    ]

    const ai = new AI({
        debugLog: console.log,
        vectorStore: _neo4jVectorStore,
        nlpModel: nlpModel,
        promptConfig: CONFIG.promptConfig,
        templateText: CONFIG.templateText,
        topK: CONFIG.similarity.topK,
    });

    for (const index in questions) {
        const question = questions[index];
        console.log(`\n${'='.repeat(80)}`);
        console.log(`📌 QUESTION: ${question}`);
        console.log('='.repeat(80));

        // Aqui é feito uma busca por similaridade, os embeddings da minha pergunta são comparados 
        // com os embeddings dos documentos que estão no grafo do Neo4j.
        const result = await ai.answerQuestion(question!);

        if(result.error) {
            console.log(`❌ Error: ${result.error}\n`);
            continue;
        }

        console.log(`💬 Answer: ${result.answer}\n`);
        await mkdir(CONFIG.output.answersFolder, { recursive: true });

        const fileName = `${CONFIG.output.answersFolder}/${CONFIG.output.fileName}-${index}-${Date.now()}.md`;

        await writeFile(fileName, result.answer!);
    }


    // Cleanup
    console.log(`\n${'='.repeat(80)}`);
    console.log("✅ Proccess finished successfully!\n");

} catch (error) {
    console.error("Error processing document:", error);
} finally {
    _neo4jVectorStore?.close();
}

